const Products = [
  {
    id: 1,
    image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    category: "backpack",
    name: "Fjallraven Backpack",
    description: "Our perfect pack for everyday use and walks in the forest.",
    type: "backpack",
    price: 3500,
  },
  {
    id: 2,
    image:
      "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    category: "men's clothing",
    name: "Mens Premium T-Shirt",
    description: "Slim-fitting style, contrast raglan long sleeve shirt",
    type: "men's shirt",
    price: 1000,
  },
  {
    id: 3,
    image: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    category: "men's clothing",
    name: "Mens Cotton Jacket",
    description: "Great outerwear jackets for Spring/Autumn/Winter",
    type: "men's shirt",
    price: 2000,
  },
  {
    id: 4,
    image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    category: "men's clothing",
    name: "Mens Casual Slim Fit",
    description: "The color could be slightly different between on the screen and in practice.",
    type: "men's clothing",
    price: 2499,
  },
  {
    id: 5,
    image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    category: "jewelry",
    name: "Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
    description: "The Naga was inspired by the mythical water dragon.",
    type: "jewelry",
    price: 5000,
  },
  {
    id: 6,
    image: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    category: "jewelry",
    name: "Solid Gold Petite Micropave",
    description: "Designed and sold by Hafeez Center in the United States",
    type: "jewelry",
    price: 3500,
  },
  {
    id: 7,
    image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    category: "jewelry",
    name: "White Gold Plated Princess",
    description: "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her.",
    type: "jewelry",
    price: 6000,
  },
  {
    id: 8,
    image: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    category: "electronics",
    name: "WD 2TB Elements Portable External Hard Drive - USB 3.0",
    description: "USB 3.0 and USB 2.0 Compatibility Fast data transfers.",
    type: "electronics",
    price: 3200,
  },
];

export default Products;
